#!/bin/bash
echo "Installing and running RSpec tests on all supported Rubies..."

CURRENT=`rvm current`

function title {
  echo -e "\n\033[1m$1\033[0m"
}

title "Ruby 1.8.7"
rvm use 1.8.7
rake install
rspec spec

title "Ruby 1.9.2"
rvm use 1.9.2
rake install
rspec spec

title "Ruby 1.9.3"
rvm use 1.9.3
rake install
rspec spec

rvm use $CURRENT
