#!/bin/bash
echo "Installing and running RSpec tests on all supported Rubies..."

CURRENT=`rvm current`

function test_ruby {
  echo -e "\n\033[1m$1\033[0m"
  rvm use $1
  rake install
  rspec spec
}

test_ruby 1.8.7
test_ruby 1.9.2
test_ruby 1.9.3

rvm use $CURRENT
